vti_encoding:SR|utf8-nl
vti_author:SR|KME\\gk
vti_timecreated:TR|07 Jan 2005 08:56:30 -0000
vti_timelastmodified:TR|12 Apr 2011 11:15:31 -0000
vti_extenderversion:SR|5.0.2.6790
vti_backlinkinfo:VX|
vti_version:SW|5.0.2.4128
vti_syncwith_localhost\\d\:\\wwwroot/d\:/wwwroot/newsletters:TR|07 Jan 2005 08:56:32 -0000
vti_syncwith_localhost\\d\:\\kmeho/d\:/kmeho/newsletters:TR|07 Jan 2005 08:56:32 -0000
vti_syncwith_gks\:80/newsletters:TR|07 Jan 2005 08:56:32 -0000
vti_syncwith_localhost\\d\:\\newsletters/d\:/newsletters:TR|07 Jan 2005 08:56:32 -0000
vti_syncwith_localhost\\d\:\\kmcho/d\:/kmcho/newsletters:TR|07 Jan 2005 08:56:32 -0000
vti_syncwith_192.168.1.29\:80/fp/newsletters:TR|07 Jan 2005 08:56:32 -0000
vti_syncwith_localhost\\d\:\\kmchofpon180211/d\:/kmchofpon180211:TR|12 Apr 2011 11:15:31 -0000
vti_modifiedby:SR|KMCHO\\Administrator
vti_nexttolasttimemodified:TW|07 Jan 2005 08:56:32 -0000
vti_lineageid:SR|{7B52F14A-7FBA-4C8A-9464-49B269E430C9}
vti_cacheddtm:TX|07 Jan 2005 08:56:32 -0000
vti_filesize:IR|5124
