vti_encoding:SR|utf8-nl
vti_author:SR|KMCHO\\gk
vti_timecreated:TR|07 Dec 2006 05:08:53 -0000
vti_timelastmodified:TR|12 Apr 2011 11:20:18 -0000
vti_extenderversion:SR|5.0.2.6790
vti_backlinkinfo:VX|
vti_syncwith_localhost\\d\:\\kmcho/d\:/kmcho/newsletters:TR|07 Dec 2006 05:08:53 -0000
vti_syncwith_gks\:80/newsletters:TR|07 Dec 2006 05:08:53 -0000
vti_syncwith_192.168.1.29\:80/fp/newsletters:TR|07 Dec 2006 05:08:53 -0000
vti_lineageid:SR|{29798F42-8DF6-451C-A2B3-6803A918D7FF}
vti_syncwith_localhost\\d\:\\kmchofpon180211/d\:/kmchofpon180211:TR|12 Apr 2011 11:20:18 -0000
vti_modifiedby:SR|KMCHO\\Administrator
vti_nexttolasttimemodified:TW|07 Dec 2006 05:08:52 -0000
vti_cacheddtm:TX|07 Dec 2006 05:08:52 -0000
vti_filesize:IR|5438
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
