vti_encoding:SR|utf8-nl
vti_author:SR|KMCHO\\gk
vti_timecreated:TR|07 Dec 2006 05:08:55 -0000
vti_timelastmodified:TR|12 Apr 2011 11:20:26 -0000
vti_extenderversion:SR|5.0.2.6790
vti_backlinkinfo:VX|
vti_syncwith_localhost\\d\:\\kmcho/d\:/kmcho/newsletters:TR|07 Dec 2006 05:08:55 -0000
vti_syncwith_gks\:80/newsletters:TR|07 Dec 2006 05:08:55 -0000
vti_syncwith_192.168.1.29\:80/fp/newsletters:TR|07 Dec 2006 05:08:55 -0000
vti_syncwith_localhost\\d\:\\kmchofpon180211/d\:/kmchofpon180211:TR|12 Apr 2011 11:20:26 -0000
vti_modifiedby:SR|KMCHO\\Administrator
vti_nexttolasttimemodified:TW|07 Dec 2006 05:08:54 -0000
vti_lineageid:SR|{7E2F1EE0-881E-4026-867F-68FB4FB911C5}
vti_cacheddtm:TX|07 Dec 2006 05:08:54 -0000
vti_filesize:IR|12224
